version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Getting Started
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - aws --version
      - echo node environment
      - echo $NODE_ENV 
      - echo DB Username
      - echo $DB_USERNAME
      - echo DB Password
      - echo $DB_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo first test codes
      - CI=true npm test
      - echo Compiling the codes
      - npm run build
      - echo Build finished, now moving to S3
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync build/ s3://sandip-demo-static-site-s3 --acl public-read